export const formation = {
  'formation.title': 'Formation',
  'formation.overline': '{language} · {coverage}',
  'formation.coverage.movements': 'five movements available',
  'formation.coverage.questions': 'stories with study questions',
  'formation.coverage.stories': 'stories',
  'formation.groups.title': 'Your groups',
  'formation.groups.add': 'Group',
  'formation.groups.addLabel': 'Create a group',
  'formation.groups.empty': 'Create a group to keep your place in the stories.',
  'formation.group.progress': 'Story {story} of {total} · next: {movement}',
  'formation.group.default': 'New group {number}',
  'formation.group.name': 'Group name',
  'formation.group.namePlaceholder': 'Like Tuesday group',
  'formation.group.rename': 'Rename',
  'formation.group.delete': 'Delete group',
  'formation.group.deleteConfirm': 'Delete {group}? Its position and notes are removed from this phone.',
  'formation.group.keep': 'Keep group',
  'formation.tracks.title': 'Tracks',
  'formation.foundations': 'Foundations',
  'formation.foundations.count': {
    one: 'Foundations · {count} story',
    other: 'Foundations · {count} stories',
  },
  'formation.foundations.about': 'Open Bible Stories with the five movements',
  'formation.foundations.tagline': 'Gather a group, press play, go deeper.',
  'formation.foundations.done': '{done} of {total} done',
  'formation.training': 'Training',
  'formation.training.about': 'Academy as a course. How to translate and check Scripture in your church.',
  'formation.training.lesson': 'Lesson {number} of {total}',
  'formation.topics': 'Topics',
  'formation.topics.about': 'Themes for deeper study.',
  'session.overline': 'Story {number} of {total}',
  'session.meta': '{group} · {language}',
  'session.keyIdea': 'Key idea',
  'session.creedalVerse': 'Creedal verse',
  'session.summary': 'Summary',
  'session.frame': 'Frame {number} of {total}',
  'session.frame.picture': 'Picture for frame {number}',
  'session.frame.previous': 'Previous frame',
  'session.frame.next': 'Next frame',
  'session.play': 'Play and discuss',
  'session.pause': 'Pause',
  'session.audio.time': '{position} / {duration}',
  'session.talk': 'Talk about it',
  'session.talk.source': 'Talk about it · {language}',
  'session.talk.studyQuestions': 'Talk about it · study questions',
  'movement.observation': 'Observation',
  'movement.translation': 'Translation',
  'movement.discourse': 'Discourse',
  'movement.theological': 'Theological',
  'movement.journal': 'Journal',
  'session.drafting': 'Drafting',
  'session.checking': 'Checking',
  'session.conclusion': 'Conclusion',
  'session.fallback.title': 'The five movements are not yet in {language}',
  'session.fallback.notYet': 'Not yet in this language',
  'session.fallback.toggle': 'Show English movements alongside',
  'session.fallback.offer': 'Show the English movements alongside the story.',
  'session.fallback.showing': 'Showing the English movements alongside the {language} story.',
  'session.fallback.needsEnglish': 'Download English to see the movements alongside.',
  'session.notes.title': 'Session notes · {group}',
  'session.notes.placeholder': 'What did the group notice?',
  'session.notes.hint': 'Stays on this phone with the group.',
  'session.notes.saved': 'Saved on this phone',
  'session.complete': 'Mark this session done',
  'session.completed': 'Session done',
  'session.nextSession': 'Next session',
  'session.chooseGroup': 'Choose a group to keep your place.',
  'session.picturesMissing':
    'Story pictures are not on this phone yet. They download once for every language.',
} as const;
