export const onboarding = {
  'onboarding.logo': 'unfoldingWord',
  'onboarding.overline': 'Open Bible translation resources',
  'onboarding.tagline': 'Every resource. Every language. One open door.',
  'onboarding.body':
    'Read, listen and share what the global church has built with unfoldingWord, in the languages you work in, online or off.',
  'onboarding.name.label': 'Your first name (optional)',
  'onboarding.name.hint': 'It stays on this phone and is used only to greet you.',
  'onboarding.choose': 'Choose your language',
  'onboarding.english': 'Continue in English',
  'onboarding.footer': 'Free. Openly licensed. No account needed.',
} as const;

export const home = {
  'home.greeting.morning': 'Good morning',
  'home.greeting.afternoon': 'Good afternoon',
  'home.greeting.evening': 'Good evening',
  'home.greeting.morning.named': 'Good morning, {name}',
  'home.greeting.afternoon.named': 'Good afternoon, {name}',
  'home.greeting.evening.named': 'Good evening, {name}',
  'home.reading.title': 'Continue reading',
  'home.reading.detail': 'Bible text with notes · {language}',
  'home.reading.action': 'Read',
  'home.reading.empty': 'Open a passage in Study and it will wait for you here.',
  'home.formation.title': 'Continue formation · {group}',
  'home.formation.story': 'Story {number}',
  'home.formation.next': 'Next: {movement}',
  'home.formation.action': 'Continue with {group}',
  'home.formation.empty': 'Create a group in Formation to walk through the stories together.',
  'home.download.progress': 'Downloading {language}',
  'home.download.percent': '{percent}%',
  'home.download.waiting': 'Connect to the internet, then tap to download.',
  'home.download.none': 'Nothing for {language} is on this phone yet.',
  'home.download.missing': 'Some resources for {language} are not on this phone yet.',
  'home.download.complete': 'Download the rest',
  'home.download.count': {
    one: '{count} of {total} resource on this phone',
    other: '{count} of {total} resources on this phone',
  },
  'home.download.ready': {
    one: '{count} resource ready offline in {language}',
    other: '{count} resources ready offline in {language}',
  },
  'home.saved.title': 'Saved',
  'home.saved.empty': 'Save a passage, article or story and it appears here.',
  'home.saved.passage': 'Bible text · {language}',
  'home.saved.word': 'Words · {language}',
  'home.saved.academy': 'Academy · {language}',
  'home.saved.story': 'Open Bible Stories · {language}',
  'home.new.title': 'What is new',
  'home.new.one': '{resource} has a newer release',
  'home.new.detail': '{newVersion} replaces {oldVersion}, {size}, when you choose to update.',
  'home.new.many': {
    one: '{count} resource has a newer release',
    other: '{count} resources have a newer release',
  },
  'home.new.action': 'Update',
  'invitation.overline': 'Impact story',
  'invitation.body':
    'Partners make resources like these free for leaders everywhere, and you can help extend the reach into the unreached.',
  'invitation.action': 'Partner with unfoldingWord',
  'invitation.dismiss': 'Not now',
  'invitation.readMore': 'Read the full story on unfoldingword.org',
} as const;
