export const languages = {
  'languages.title': 'Languages',
  'languages.overline': {
    one: '{count} language · {language} selected',
    other: '{count} languages · {language} selected',
  },
  'languages.overline.onboarding': 'Choose the language you read in',
  'languages.search': 'Search languages',
  'languages.resources': { one: '{count} resource', other: '{count} resources' },
  'languages.row': '{english} · {resources} · {size}',
  'languages.select': 'Read in {language}',
  'languages.selected': 'Selected',
  'languages.noMatch': 'No language matches {query}.',
  'languages.offline': 'You are offline, so only languages already on this phone are listed.',
  'languages.coverage':
    "{available} of the app's {total} languages have published content today. The others appear as soon as they do.",
  'languages.download': 'Download',
  'languages.remove': 'Remove',
  'languages.removeConfirm': 'Remove {language} from this phone? You can download it again later.',
  'languages.update': 'Update',
  'languages.updateDetail': '{version} is ready, {size}.',
  'languages.installing': 'Checking and installing',
  'storage.title': 'Storage',
  'storage.summary': '{used} on this phone · {free} free',
  'storage.language': '{language} · {size}',
  'storage.images': 'Story pictures · {size}, shared',
  'storage.audio': '{language} audio · {size}',
  'storage.original': '{resource} · {size}',
  'storage.empty': 'Nothing is downloaded yet.',
  'storage.low': 'Space on this phone is running low.',
  'transfer.open': 'Send to another phone',
  'transfer.title': 'Send to another phone',
  'transfer.overline': 'No internet needed',
  'transfer.send': 'Send',
  'transfer.receive': 'Receive',
  'transfer.receive.title': 'Receive from another phone',
  'transfer.choose': '{language} · choose what goes',
  'transfer.selected': {
    one: '{count} resource selected · {size}',
    other: '{count} resources selected · {size}',
  },
  'transfer.note':
    'Works between iPhone and Android in both directions. Licence and attribution go with every item.',
  'transfer.app': 'Send this app too',
  'transfer.app.about': 'The other phone can install it without a store.',
  'transfer.app.ios': 'iPhone does not allow sending the app itself. Resources can still go.',
  'transfer.find': 'Find a nearby phone',
  'transfer.looking': 'Looking for a nearby phone',
  'transfer.looking.hint': 'Open Receive on the other phone and keep the phones close.',
  'transfer.peer': 'Nearby phone {number}',
  'transfer.permission': 'The app uses nearby access only while you transfer.',
  'transfer.waiting': 'Waiting for the other phone to accept',
  'transfer.offer.title': 'A nearby phone is offering {language}',
  'transfer.offer.size': {
    one: '{count} resource, {size}',
    other: '{count} resources, {size}',
  },
  'transfer.accept': 'Accept',
  'transfer.decline': 'Not now',
  'transfer.sending': 'Sending {percent}%',
  'transfer.receiving': 'Receiving {percent}%',
  'transfer.stop': 'Stop',
  'transfer.sent': 'Sent. {language} is ready on the other phone.',
  'transfer.received': '{language} is ready to read.',
  'transfer.openLanguage': 'Open {language}',
  'transfer.stopped': 'The transfer stopped before it finished. Nothing partial was kept.',
  'transfer.app.received': 'The app is on the other phone. Install it there, then send resources.',
  'share.passage': 'Share passage',
  'share.story': 'Share story',
  'share.asText': 'Share as text',
  'share.asAudio': 'Share as audio',
  'share.note': 'Sent with its licence and attribution, and a short link to get the app.',
  'share.noAudio': 'There is no audio for this one yet.',
  'share.payload.attribution': '{resource} by {publisher}, {version}, {licence}.',
  'share.payload.link': 'Get the app: {link}',
} as const;
