export const languages = {
  'languages.title': 'Languages',
  'languages.overline': {
    one: '{count} language · {language} selected',
    other: '{count} languages · {language} selected',
  },
  'languages.overline.onboarding': 'Choose the language you read in',
  'languages.search': 'Search languages',
  'languages.resources': { one: '{count} resource', other: '{count} resources' },
  'languages.row': '{english} · {resources} · {size}',
  'languages.select': 'Read in {language}',
  'languages.selected': 'Selected',
  'languages.noMatch': 'No language matches {query}.',
  'languages.offline': 'You are offline, so only languages already on this phone are listed.',
  'languages.coverage':
    "{available} of the app's {total} languages have published content today, and the others appear as soon as they do.",
  'languages.download': 'Download',
  'languages.remove': 'Remove',
  'languages.removeConfirm': 'Remove {language} from this phone until you download it again?',
  'languages.update': 'Update',
  'languages.updateDetail': '{version} is ready, {size}.',
  'languages.installing': 'Checking and installing',
  'storage.title': 'Storage',
  'storage.summary': '{used} on this phone · {free} free',
  'storage.language': '{language} · {size}',
  'storage.images': 'Story pictures · {size}, shared',
  'storage.audio': '{language} audio · {size}',
  'storage.original': '{resource} · {size}',
  'storage.empty': 'Nothing is downloaded yet.',
  'storage.low': 'Space on this phone is running low.',
  'transfer.open': 'Send to another phone',
  'transfer.title': 'Send to another phone',
  'transfer.overline': 'No internet needed',
  'transfer.send': 'Send',
  'transfer.receive': 'Receive',
  'transfer.receive.title': 'Receive from another phone',
  'transfer.choose': '{language} · choose what goes',
  'transfer.selected': {
    one: '{count} resource selected · {size}',
    other: '{count} resources selected · {size}',
  },
  'transfer.note':
    'Works between iPhone and Android in both directions, with licence and attribution on every item.',
  'transfer.app': 'Send this app too',
  'transfer.app.about': 'The other phone can install it without a store.',
  'transfer.app.ios': 'iPhone does not allow sending the app itself, but resources can still go.',
  'transfer.find': 'Find a nearby phone',
  'transfer.looking': 'Looking for a nearby phone',
  'transfer.looking.hint': 'Open Receive on the other phone and keep the phones close.',
  'transfer.peer': 'Nearby phone {number}',
  'transfer.code': 'Code {code}',
  'transfer.code.hint': 'Check that the other phone shows the same code.',
  'transfer.nothing': 'Download a language first, then you can send it to another phone.',
  'transfer.permission': 'The app uses nearby access only while you transfer.',
  'transfer.waiting': 'Waiting for the other phone to accept',
  'transfer.offer.title': 'A nearby phone is offering {language}',
  'transfer.offer.size': {
    one: '{count} resource, {size}',
    other: '{count} resources, {size}',
  },
  'transfer.accept': 'Accept',
  'transfer.decline': 'Not now',
  'transfer.sending': 'Sending {percent}%',
  'transfer.receiving': 'Receiving {percent}%',
  'transfer.stop': 'Stop',
  'transfer.sent': '{language} is sent and ready on the other phone.',
  'transfer.received': '{language} is ready to read.',
  'transfer.openLanguage': 'Open {language}',
  'transfer.stopped': 'The transfer stopped before it finished, and nothing partial was kept.',
  'transfer.app.received': 'The app is on the other phone, so install it there and then send resources.',
  'share.passage': 'Share passage',
  'share.story': 'Share story',
  'share.asText': 'Share as text',
  'share.asAudio': 'Share as audio',
  'share.note': 'Sent with its licence and attribution, and a short link to get the app.',
  'share.noAudio': 'There is no audio for this one yet.',
  'share.payload.attribution': '{resource} by {publisher}, {version}, {licence}.',
  'share.payload.link': 'Get the app: {link}',
  'transfer.app.ready': 'The app arrived on this phone ({size}) and is ready to install.',
  'transfer.network': 'Put both phones on the same Wi-Fi or hotspot first.',
  'transfer.localNetwork.prompt':
    'The app looks for the other phone on your Wi-Fi or hotspot only while you send or receive.',
  'transfer.address': 'If the other phone does not find this one, type {address} there.',
  'transfer.address.qr': 'Picture code for {address} to scan with the camera on the other phone.',
  'transfer.typed': 'Type an address',
  'transfer.typed.address': 'Address from the other phone',
  'transfer.typed.code': 'Code from the other phone',
  'transfer.typed.connect': 'Connect',
  'transfer.typed.invalid': 'Type the address and the six-digit code as the other phone shows them.',
  'transfer.app.install': 'Install the app',
  'transfer.app.install.opened': 'The installer is open, so follow its steps to finish.',
  'transfer.app.install.unsupported':
    'This copy of the app cannot open the installer, so get the app from its store instead.',
  'languages.import.title': 'From a file',
  'languages.import': 'Import from a file',
  'languages.import.about': 'Install a Scripture Burrito archive (.zip) you saved or were given.',
  'languages.import.opened': 'Install {name}, the file you opened, on this phone?',
  'languages.import.install': 'Install',
  'languages.import.done': 'Installed from the file and ready to read offline.',
  'languages.release': '{publisher} · {version}',
  'languages.missing.title': 'Not yet on this phone',
  'languages.missing.about': 'Part of {language} did not download, and you can try again.',
  'languages.more.title': 'More to download',
  'languages.more.about':
    'Other publishers and extra resources for {language}, downloaded only when you choose them.',
} as const;
