export const study = {
  'study.text.literal': 'Close to the original',
  'study.text.simplified': 'Everyday words',
  'study.text.choice': 'Choose how the Bible text reads',
  'study.nav.reference': '{book} {chapter}',
  'study.nav.choose': 'Choose a book and chapter',
  'study.nav.previous': 'Previous chapter',
  'study.nav.next': 'Next chapter',
  'study.nav.oldTestament': 'Old Testament',
  'study.nav.newTestament': 'New Testament',
  'study.nav.chapter': 'Chapter {chapter}',
  'study.nav.verse': 'Verse {verse}',
  'study.passage.save': 'Save this passage',
  'study.passage.share': 'Share this passage',
  'study.passage.missing': 'This passage is not in {language} yet.',
  'study.passage.notDownloaded': 'Download {language} to read this passage offline.',
  'study.helps.notes': 'Notes',
  'study.helps.wordLinks': 'Word links',
  'study.helps.questions': 'Questions',
  'study.helps.heading': '{helps} · verse {verse}',
  'study.helps.tapTerm': 'Tap a term to open its article.',
  'study.helps.noNotes': 'No notes for this verse.',
  'study.helps.noWordLinks': 'No word links for this verse.',
  'study.helps.noQuestions': 'No questions for this verse.',
  'study.helps.notDownloaded': 'Helps for this passage are not on this phone yet.',
  'study.audio.play': 'Play audio',
  'study.audio.pause': 'Pause audio',
  'study.audio.label': '{reference} · audio',
  'study.audio.streaming': 'Streaming',
  'study.audio.onPhone': 'On this phone',
  'study.audio.time': '{position} / {duration}',
  'study.audio.download': 'Download audio for offline',
  'study.audio.downloading': 'Downloading audio',
  'study.audio.offline': 'Audio streams when you are online. Download it to listen offline.',
  'library.open': 'Library',
  'library.title': 'Library',
  'library.overline': {
    one: '{language} · {count} resource',
    other: '{language} · {count} resources',
  },
  'library.footer':
    'All content CC BY-SA 4.0, attributed to the organization that published it. unfoldingWord resources are listed first.',
  'library.about': 'About this library',
  'library.meta': '{publisher} · {version}',
  'library.optional': 'Optional download',
  'library.notDownloaded': 'Not downloaded',
  'library.downloading': 'Downloading',
  'library.books': { one: '{count} book', other: '{count} books' },
  'library.articles': { one: '{count} article', other: '{count} articles' },
  'library.stories': { one: '{count} story', other: '{count} stories' },
  'resource.literal': 'Bible, close to the original',
  'resource.literal.about': 'Literal text aligned to the source, so notes land on the right words.',
  'resource.simplified': 'Bible, everyday words',
  'resource.simplified.about': 'Simplified text for reading aloud and teaching.',
  'resource.notes': 'Notes',
  'resource.notes.about': 'Help with hard passages, attached to each verse.',
  'resource.wordLinks': 'Word links',
  'resource.wordLinks.about': 'Words in the text linked to their entries in Words.',
  'resource.words': 'Words',
  'resource.words.about': 'Key terms and names explained, linked from the text.',
  'resource.questions': 'Questions',
  'resource.questions.about': 'Check understanding after each passage.',
  'resource.academy': 'Academy',
  'resource.academy.about': 'How to translate and check Scripture in your church.',
  'resource.stories': 'Open Bible Stories',
  'resource.stories.about': 'Fifty stories from creation to the church, with pictures.',
  'resource.storyHelps': 'Story helps',
  'resource.storyHelps.about': 'Questions and notes for each story.',
  'resource.formation': 'Five movements',
  'resource.formation.about': 'Questions that walk a group through each story in five movements.',
  'resource.images': 'Story pictures',
  'resource.images.about': 'Shared by every language and downloaded once.',
  'resource.audio': 'Audio',
  'resource.audio.about': 'A separate download for each resource.',
  'resource.hebrew': 'Hebrew Old Testament',
  'resource.greek': 'Greek New Testament',
  'resource.original.about': 'Plain text, outside the language pack.',
  'article.word': 'Words',
  'article.academy': 'Academy',
  'article.meta': '{kind} · {language}',
  'article.save': 'Save this article',
  'article.links': 'Linked from this article',
  'article.notDownloaded': 'This article is not on this phone yet.',
  'article.linkMissing': 'This link points to something that is not on this phone.',
  'search.placeholder': 'Reference or title, like Ruth 2 or covenant',
  'search.label': 'Search passages, words, lessons and stories',
  'search.empty': 'Type a reference like Ruth 2, or the title of a word or story.',
  'search.noResults': 'Nothing on this phone matches {query}.',
  'search.passages': 'Passages',
  'search.titles': 'Titles',
  'search.inText': 'Inside the text',
  'search.kind.passage': 'Bible text · {language}',
  'search.kind.word': 'Words',
  'search.kind.academy': 'Academy',
  'search.kind.story': 'Open Bible Stories',
  'search.fullText.title': 'Search inside every downloaded text',
  'search.fullText.detail': 'Builds an index on this phone, about {size} for {language}.',
  'search.fullText.building': 'Building the index',
  'search.fullText.on': 'Search inside every downloaded text is on.',
  'study.helps.showResponse': 'Show the answer',
  'study.helps.hideResponse': 'Hide the answer',
  'study.noLanguage': 'Choose a language to start reading.',
  'study.noLanguage.action': 'Choose a language',
  'library.download': 'Download {resource}',
  'library.onPhone': 'On this phone',
  'search.fullText.inSettings': 'Turn it on in Settings. The index stays on this phone.',
  'study.frame.picture': 'Picture for frame {number}',
} as const;
