export const isoNames: Readonly<Record<string, string>> = {
  aa: 'Afar',
  ab: 'Abkhaz',
  af: 'Afrikaans',
  ak: 'Akan',
  am: 'Amharic',
  an: 'Aragonese',
  ar: 'Arabic',
  as: 'Assamese',
  av: 'Avar',
  ay: 'Aymara',
  az: 'Azerbaijani',
  ba: 'Bashkir',
  be: 'Belarusian',
  bg: 'Bulgarian',
  bi: 'Bislama',
  bm: 'Bambara',
  bn: 'Bengali',
  bo: 'Tibetan',
  br: 'Breton',
  bs: 'Bosnian',
  ca: 'Catalan',
  ce: 'Chechen',
  ch: 'Chamorro',
  co: 'Corsican',
  cr: 'Cree',
  cs: 'Czech',
  cu: 'Church Slavonic',
  cv: 'Chuvash',
  cy: 'Welsh',
  da: 'Danish',
  de: 'German',
  dv: 'Dhivehi',
  dz: 'Dzongkha',
  ee: 'Ewe',
  el: 'Greek',
  en: 'English',
  eo: 'Esperanto',
  es: 'Spanish',
  et: 'Estonian',
  eu: 'Basque',
  fa: 'Farsi',
  ff: 'Fula',
  fi: 'Finnish',
  fj: 'Fijian',
  fo: 'Faroese',
  fr: 'French',
  fy: 'Western Frisian',
  ga: 'Irish',
  gd: 'Scottish Gaelic',
  gl: 'Galician',
  gn: 'Guarani',
  gu: 'Gujarati',
  gv: 'Manx',
  ha: 'Hausa',
  he: 'Hebrew',
  hi: 'Hindi',
  ho: 'Hiri Motu',
  hr: 'Croatian',
  ht: 'Haitian Creole',
  hu: 'Hungarian',
  hy: 'Armenian',
  hz: 'Herero',
  id: 'Indonesian',
  ig: 'Igbo',
  ii: 'Nuosu',
  ik: 'Inupiaq',
  is: 'Icelandic',
  it: 'Italian',
  iu: 'Inuktitut',
  ja: 'Japanese',
  jv: 'Javanese',
  ka: 'Georgian',
  kg: 'Kongo',
  ki: 'Kikuyu',
  kj: 'Kwanyama',
  kk: 'Kazakh',
  kl: 'Greenlandic',
  km: 'Khmer',
  kn: 'Kannada',
  ko: 'Korean',
  kr: 'Kanuri',
  ks: 'Kashmiri',
  ku: 'Kurdish',
  kv: 'Komi',
  kw: 'Cornish',
  ky: 'Kyrgyz',
  la: 'Latin',
  lb: 'Luxembourgish',
  lg: 'Ganda',
  li: 'Limburgish',
  ln: 'Lingala',
  lo: 'Lao',
  lt: 'Lithuanian',
  lu: 'Luba-Katanga',
  lv: 'Latvian',
  mg: 'Malagasy',
  mh: 'Marshallese',
  mi: 'Maori',
  mk: 'Macedonian',
  ml: 'Malayalam',
  mn: 'Mongolian',
  mr: 'Marathi',
  ms: 'Malay',
  mt: 'Maltese',
  my: 'Burmese',
  na: 'Nauruan',
  nb: 'Norwegian Bokmål',
  nd: 'North Ndebele',
  ne: 'Nepali',
  ng: 'Ndonga',
  nl: 'Dutch',
  nn: 'Norwegian Nynorsk',
  no: 'Norwegian',
  nr: 'South Ndebele',
  nv: 'Navajo',
  ny: 'Chichewa',
  oc: 'Occitan',
  oj: 'Ojibwe',
  om: 'Oromo',
  or: 'Odia',
  os: 'Ossetian',
  pa: 'Punjabi',
  pi: 'Pali',
  pl: 'Polish',
  ps: 'Pashto',
  pt: 'Portuguese',
  qu: 'Quechua',
  rm: 'Romansh',
  rn: 'Kirundi',
  ro: 'Romanian',
  ru: 'Russian',
  rw: 'Kinyarwanda',
  sa: 'Sanskrit',
  sc: 'Sardinian',
  sd: 'Sindhi',
  se: 'Northern Sami',
  sg: 'Sango',
  si: 'Sinhala',
  sk: 'Slovak',
  sl: 'Slovenian',
  sm: 'Samoan',
  sn: 'Shona',
  so: 'Somali',
  sq: 'Albanian',
  sr: 'Serbian',
  ss: 'Swati',
  st: 'Sesotho',
  su: 'Sundanese',
  sv: 'Swedish',
  sw: 'Swahili',
  ta: 'Tamil',
  te: 'Telugu',
  tg: 'Tajik',
  th: 'Thai',
  ti: 'Tigrinya',
  tk: 'Turkmen',
  tl: 'Tagalog',
  tn: 'Tswana',
  to: 'Tongan',
  tr: 'Turkish',
  ts: 'Tsonga',
  tt: 'Tatar',
  tw: 'Twi',
  ty: 'Tahitian',
  ug: 'Uyghur',
  uk: 'Ukrainian',
  ur: 'Urdu',
  uz: 'Uzbek',
  ve: 'Venda',
  vi: 'Vietnamese',
  wa: 'Walloon',
  wo: 'Wolof',
  xh: 'Xhosa',
  yi: 'Yiddish',
  yo: 'Yoruba',
  za: 'Zhuang',
  zh: 'Chinese',
  zu: 'Zulu',
  ace: 'Acehnese',
  ach: 'Acholi',
  acm: 'Mesopotamian Arabic',
  adi: 'Adi',
  aeb: 'Tunisian Arabic',
  ajp: 'South Levantine Arabic',
  alz: 'Alur',
  apc: 'North Levantine Arabic',
  apd: 'Sudanese Arabic',
  arb: 'Standard Arabic',
  arc: 'Aramaic',
  arq: 'Algerian Arabic',
  ars: 'Najdi Arabic',
  ary: 'Moroccan Arabic',
  arz: 'Egyptian Arabic',
  awa: 'Awadhi',
  azb: 'South Azerbaijani',
  bal: 'Baluchi',
  ban: 'Balinese',
  bbc: 'Batak Toba',
  bcl: 'Central Bikol',
  bem: 'Bemba',
  bft: 'Balti',
  bgc: 'Haryanvi',
  bhb: 'Bhili',
  bho: 'Bhojpuri',
  bik: 'Bikol',
  bin: 'Edo',
  bjn: 'Banjar',
  bns: 'Bundeli',
  bqi: 'Bakhtiari',
  bra: 'Braj',
  brh: 'Brahui',
  brx: 'Bodo',
  bug: 'Buginese',
  cak: 'Kaqchikel',
  ceb: 'Cebuano',
  cgg: 'Chiga',
  chr: 'Cherokee',
  ckb: 'Central Kurdish',
  cmn: 'Mandarin Chinese',
  cnh: 'Hakha Chin',
  crs: 'Seychellois Creole',
  ctd: 'Tedim Chin',
  ctg: 'Chittagonian',
  dag: 'Dagbani',
  dcc: 'Deccani',
  din: 'Dinka',
  doi: 'Dogri',
  dyu: 'Dyula',
  efi: 'Efik',
  fat: 'Fante',
  fil: 'Filipino',
  fon: 'Fon',
  fuv: 'Nigerian Fulfulde',
  gaa: 'Ga',
  gax: 'Borana Oromo',
  gbm: 'Garhwali',
  gom: 'Goan Konkani',
  gon: 'Gondi',
  grc: 'Ancient Greek',
  grt: 'Garo',
  gsw: 'Swiss German',
  gug: 'Paraguayan Guarani',
  guz: 'Gusii',
  hak: 'Hakka Chinese',
  haw: 'Hawaiian',
  hay: 'Haya',
  haz: 'Hazaragi',
  hbo: 'Ancient Hebrew',
  hil: 'Hiligaynon',
  hmn: 'Hmong',
  hne: 'Chhattisgarhi',
  hno: 'Northern Hindko',
  hoc: 'Ho',
  ibb: 'Ibibio',
  ilo: 'Ilocano',
  kab: 'Kabyle',
  kac: 'Kachin',
  kam: 'Kamba',
  kbp: 'Kabiyè',
  kde: 'Makonde',
  kek: 'Qʼeqchiʼ',
  kfy: 'Kumaoni',
  kha: 'Khasi',
  khr: 'Kharia',
  kln: 'Kalenjin',
  kmb: 'Kimbundu',
  kmr: 'Northern Kurdish',
  kok: 'Konkani',
  kqn: 'Kaonde',
  kri: 'Krio',
  kru: 'Kurukh',
  ksb: 'Shambala',
  ksw: 'Sʼgaw Karen',
  lbj: 'Ladakhi',
  lep: 'Lepcha',
  lif: 'Limbu',
  lmn: 'Lambadi',
  loz: 'Lozi',
  lrc: 'Northern Luri',
  lua: 'Luba-Lulua',
  lun: 'Lunda',
  luo: 'Luo',
  lus: 'Mizo',
  luy: 'Luyia',
  mad: 'Madurese',
  mag: 'Magahi',
  mai: 'Maithili',
  mam: 'Mam',
  mdh: 'Maguindanao',
  men: 'Mende',
  mer: 'Meru',
  mfe: 'Morisyen',
  min: 'Minangkabau',
  mni: 'Manipuri',
  mnw: 'Mon',
  mos: 'Mooré',
  mrw: 'Maranao',
  mup: 'Malvi',
  mwr: 'Marwari',
  mzn: 'Mazanderani',
  nan: 'Min Nan Chinese',
  nap: 'Neapolitan',
  new: 'Newar',
  njz: 'Nyishi',
  nso: 'Northern Sotho',
  nup: 'Nupe',
  nus: 'Nuer',
  nym: 'Nyamwezi',
  nyn: 'Nyankole',
  pag: 'Pangasinan',
  pam: 'Kapampangan',
  pap: 'Papiamento',
  pcm: 'Nigerian Pidgin',
  pes: 'Iranian Persian',
  pis: 'Pijin',
  pnb: 'Western Punjabi',
  prs: 'Dari',
  pwo: 'Pwo Karen',
  quc: 'Kʼicheʼ',
  quy: 'Ayacucho Quechua',
  quz: 'Cusco Quechua',
  raj: 'Rajasthani',
  rkt: 'Rangpuri',
  rmn: 'Balkan Romani',
  rom: 'Romani',
  sas: 'Sasak',
  sat: 'Santali',
  sck: 'Sadri',
  sdh: 'Southern Kurdish',
  shi: 'Tachelhit',
  shk: 'Shilluk',
  shn: 'Shan',
  sid: 'Sidamo',
  skr: 'Saraiki',
  snk: 'Soninke',
  srn: 'Sranan Tongo',
  suk: 'Sukuma',
  sus: 'Susu',
  swc: 'Congo Swahili',
  swh: 'Swahili',
  syl: 'Sylheti',
  tcy: 'Tulu',
  tem: 'Temne',
  tet: 'Tetum',
  tiv: 'Tiv',
  tpi: 'Tok Pisin',
  tsg: 'Tausug',
  tum: 'Tumbuka',
  tzh: 'Tzeltal',
  tzm: 'Central Atlas Tamazight',
  tzo: 'Tzotzil',
  umb: 'Umbundu',
  unr: 'Mundari',
  urh: 'Urhobo',
  uzs: 'Southern Uzbek',
  vmw: 'Makhuwa',
  wal: 'Wolaytta',
  war: 'Waray',
  wuu: 'Wu Chinese',
  xog: 'Soga',
  yua: 'Yucatec Maya',
  yue: 'Cantonese',
  zgh: 'Standard Moroccan Tamazight',
  zne: 'Zande',
};
