const englishNames: Readonly<Record<string, string>> = {
  am: 'Amharic',
  ar: 'Arabic',
  as: 'Assamese',
  bn: 'Bengali',
  ceb: 'Cebuano',
  cs: 'Czech',
  de: 'German',
  'el-x-koine': 'Koine Greek',
  en: 'English',
  es: 'Spanish',
  'es-419': 'Spanish (Latin America)',
  fa: 'Farsi',
  fr: 'French',
  grc: 'Ancient Greek',
  gu: 'Gujarati',
  ha: 'Hausa',
  hbo: 'Ancient Hebrew',
  he: 'Hebrew',
  hi: 'Hindi',
  hu: 'Hungarian',
  id: 'Indonesian',
  ig: 'Igbo',
  ilo: 'Ilocano',
  it: 'Italian',
  ja: 'Japanese',
  km: 'Khmer',
  kn: 'Kannada',
  ko: 'Korean',
  ln: 'Lingala',
  lo: 'Lao',
  mg: 'Malagasy',
  ml: 'Malayalam',
  mr: 'Marathi',
  ms: 'Malay',
  my: 'Burmese',
  ne: 'Nepali',
  nl: 'Dutch',
  or: 'Odia',
  pa: 'Punjabi',
  pl: 'Polish',
  pt: 'Portuguese',
  'pt-br': 'Portuguese (Brazil)',
  ro: 'Romanian',
  ru: 'Russian',
  rw: 'Kinyarwanda',
  sw: 'Swahili',
  ta: 'Tamil',
  te: 'Telugu',
  th: 'Thai',
  tl: 'Tagalog',
  tpi: 'Tok Pisin',
  tr: 'Turkish',
  uk: 'Ukrainian',
  ur: 'Urdu',
  vi: 'Vietnamese',
  yo: 'Yoruba',
  zh: 'Chinese',
  zu: 'Zulu',
};

export function englishNameOf(language: string, autonym: string): string {
  const tag = language.toLowerCase();
  const base = tag.split('-')[0] ?? tag;
  return englishNames[tag] ?? englishNames[base] ?? autonym;
}
